export { default as largeClasses } from 'assets/classes.json'
export { default as tinyClasses } from 'assets/classesTiny.json'
export { default as demoClasses } from 'assets/classesDemo.json'
export { default as largeVocabulary } from 'assets/vocabulary.json'
export { default as tinyVocabulary } from 'assets/vocabularyTiny.json'
export { default as demoVocabulary } from 'assets/vocabularyDemo.json'

export const SERVICE_CONTRIBUTION = 'contribution'
export const SERVICE_CATEGORIZE = 'categorize'
export const SERVICE_AGGREGATION = 'aggregation'
export const SERVICE_RECEIVE_SHARES = 'receiveShares'
export const SERVICE_OBSERVE = 'observe'

export { createLogger } from './utils'
export * from './files'
